### ISSUE TITLE
Getting a cache error 

### ISSUE THREAD

**Issue by Saketh-Gurram** [saa-97/Sanitizer-Robot-ROS2#1]
I am running ROS2 Humble on Ubuntu 22.04. I have git cloned the repo to my ros2_ws directory and am compiling it but am getting this error ,Kindly help me out 

![Screenshot from 2024-08-20 11-19-27](https://github.com/user-attachments/assets/5df15c30-a077-4eb5-b6c9-856b539c6e78)

**Comment by saa-97** [comment]
It looks like you have two directories where 'explore' is installed. I would suggest that you keep one package only and to follow the given instructions by using `colcon build --packages-select <package name>`.

**Comment by Saketh-Gurram** [comment]
I am also facing an issue when running the big house it says the package is not available am unable to find the repository to download kindly help me
